var validWords = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", 
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", 
  "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", 
  "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", 
  "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", 
  "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", 
  "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", 
  "Croatia", "Cuba", "Cyprus", "Czech Republic", "Democratic Republic of the Congo", 
  "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", 
  "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", 
  "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", 
  "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", 
  "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", 
  "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", 
  "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", 
  "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", 
  "Korea, South", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", 
  "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", 
  "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", 
  "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", 
  "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", 
  "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", 
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", 
  "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", 
  "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", 
  "Paraguay", "Peru", "Philippines", "Poland", "Portugal", 
  "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", 
  "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", 
  "San Marino", "Sao Tome and Principe", "Saudi Arabia", 
  "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", 
  "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", 
  "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", 
  "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", 
  "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", 
  "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", 
  "Ukraine", "United Arab Emirates", "United Kingdom", 
  "United States", "Uruguay", "Uzbekistan", "Vanuatu", 
  "Vatican City", "Venezuela", "Vietnam", "Yemen", 
  "Zambia", "Zimbabwe"
];
var validWords2 =['Abadon', 'Abdon', 'Ábel', 'Abelard', 'Abigail', 'Abiha', 'Abraham, 'Abrahám', 'Absolon', 'Absolón', 'Adalbert', 'Adam', 'Adéla', 'Adin', 'Adina', 'Adolf', 'Adrian', 'Adrián', 'Adriana', 'Adrien', 'Adriena', 'Agáta', 'Agaton', 'Aglaja', 'Achil', 'Achiles', 'Aida', 'Alan', 'Alban', 'Albert', 'Albín', 'Albína', 'Albrecht', 'Aldo', 'Alen', 'Alena', 'Aleš', 'Alex', 'Alexandr', 'Alexandra', 'Alexej', 'Alfons', 'Alfréd', 'Alice', 'Alida', 'Alin', 'Alina', 'Alois', 'Aloisie', 'Alruna', 'Alva', 'Alvar', 'Alvin', 'Alyson', 'Alžběta', 'Amadeus', 'Amálie', 'Amanda', 'Amát', 'Ambrož', 'Amon', 'Amos', 'Anabela', 'Anastázie', 'Anděla', 'Andrea', 'Andreas', 'Andrei', 'Andrej', 'Aneta', 'Anežka', 'Angela', 'Angus', 'Anita', 'Anna', 'Annaliesa', 'Annika', 'Antal', 'Antonie', 'Antonín', 'Apolena', 'Apolo', 'Arabela', 'Aranka', 'Areta', 'Ariadna', 'Arian', 'Ariana', 'Ariela', 'Arion', 'Arleta', 'Armando', 'Armida', 'Armin', 'Arnold', 'Arnošt', 'Aron', Árón, 'Aaron', 'Arpád', 'Artur', 'Astrid', 'Atila', 'Atilla', 'Attila', 'Augustin', 'Augustina', 'Augustýn', 'Aurelia', 'Aurelie', 'Aurelio', 'Aurora', 'Axel', 'Aya', 'Aisha', 'Babeta', 'Baek', 'Baltazar', 'Barabáš', 'Barbora', 'Bartoloměj', 'Beáta', 'Bedřich', 'Bedřiška', 'Bela', 'Běla', 'Belinda', 'Benedikt', 'Benjamin', 'Beno', 'Berenika', 'Bernadeta', 'Bernard', 'Berta', 'Bertram', 'Bianka', 'Bibiana', 'Blahomil', 'Blahomír', 'Blahoslav', 'Blanka', 'Blažej', 'Blažena', 'Bob', 'Bohdan', 'Bohdana', 'Bohuchval', 'Bohumil', 'Bohumila', 'Bohumír', 'Bohuslav', 'Bohuslava', 'Bojan', 'Bolemír', 'Boleslav', 'Bonaventura', 'Bonifác', 'Boris', 'Borislav', 'Bořek', 'Bořivoj', 'Božena', 'Božetěch', 'Božidar', 'Božidara', 'Brigita', 'Bratislav', 'Bronislav', 'Bruce', 'Brunhilda', 'Bruno', 'Bryan', 'Břetislav', 'Bystrík', 'Can', 'Carmen', 'Cecil', 'Cecílie', 'Celestýn', 'Celestýna, Celestina', 'Crha', 'Ctibor', 'Ctirad', 'Ctislav', 'Cyprián', 'Cyril', 'Cyrila', 'Čeněk', 'Česlav', 'Česlava', 'Čestmír', 'Dag', 'Dagmar', 'Daisy', 'Dalibor', 'Dalimil', 'Dan', 'Dana', 'Daniel', 'Daniela', 'Danuše', 'Darina', 'Darja', 'David', 'Deana', 'Denis', 'Denisa', 'Deodatus', 'Diana', 'Dimitris', 'Dita', 'Dmitr', 'Dobromil', 'Dobromila', 'Dobroslav', 'Dominik', 'Dominika', 'Donna', 'Dorian', 'Dorin', 'Dorota', 'Doubravka', 'Drahomír', 'Drahomíra', 'Drahoslav', 'Drahoslava', 'Dušan', 'Džamil', 'Džamila', 'Edita', 'Eduard', 'Edvin', 'Edwulf', 'Egon', 'Eithne', 'Ela', 'Ella', 'Elen', 'Eleonora', 'Elena', 'Eli', 'Eliáš', 'Elisa', 'Elisabet', 'Elisabeta', 'Eliška', 'Elke', 'Ellen', 'Elza', 'Ema', 'Emanuel', 'Emil', 'Emílie', 'Emily', 'Emma', 'Ena', 'Engelbert', 'Erik', 'Erika', 'Ervín', 'Ester', 'Etel', 'Euniké', 'Eva', 'Evelína', 'Evžen', 'Evžénie', 'Eydís', 'Elvis', 'Fabian', 'Fabio', 'Felicia', 'Felix', 'Ferdinand', 'Filip', 'Filipa', 'Fiona', 'Fjodor', 'Florian, Florián', 'Floriana', 'Florin', 'František', 'Františka', 'Fridolín', 'Freddie', 'Gabriel', 'Gabriela', 'Gabriella', 'Gaster', 'Geppetto', 'Gerda', 'Gertruda', 'Gita', 'Gizela', 'Glauco', 'Glorie, Glórie', 'Godric', 'Gorazd', 'Gordana', 'Grace', 'Gustav', 'Gwenda', 'Hadrián', 'Hana', 'Hanuš', 'Haštal', 'Háta', 'Havel', 'Heda', 'Hedvika', 'Helena', 'Helga', 'Herbert', 'Hermína', 'Hermiona', 'Heřman', 'Hortenzie', 'Horymír', 'Hostivín', 'Hubert', 'Hugo', 'Hynek', 'Chaim', 'Chajim', 'Charlie', 'Charlotte', 'Cheyenne', 'Christie', 'Christo', 'Chrudoš', 'Chřen', 'Ida', 'Idunn', 'Ignác', 'Ignácie', 'Igor', 'Ilja', 'Ilona', 'Ingemar', 'Ingrid', 'Inka', 'Irena', 'Iris', 'Irma', 'Irmhild', 'Isabela', 'Isabella', 'Isolda, Isolde', 'Iška', 'Iulian', 'Iva', 'Ivan', 'Ivana', 'Iveta', 'Ivo', 'Ivona', 'Izabela', 'Jacob', 'Jáchym', 'Jakub', 'Jakubka', 'Jan', 'Jana', 'Jarmil', 'Jarmila', 'Jarolím', 'Jaromír', 'Jaromíra', 'Jaroslav', 'Jaroslava', 'Jasmin (jméno), Jasmína', 'Jeroným', 'Jessika', 'Ješek', 'Jin', 'Jindra', 'Jindřich', 'Jindřiška', 'Jiří', 'Jiřina', 'Jitka', 'Johana', 'John', 'Jolana', 'Jonáš', 'Jorga', 'Jorik', 'Josef', 'Joshua', 'Jovana', 'Judita', 'Juliana', 'Julie', 'Julia', 'Julius', 'Jun', 'Justýna', 'Kamil', 'Kamila', 'Karel', 'Karina', 'Karla', 'Karolína', 'Kaspar', 'Kašpar', 'Kateřina', 'Kazimír', 'Kelly', 'Kevin', 'Klára', 'Klaudie', 'Klement', 'Kliment', 'Konstantin', 'Koridon', 'Krasimír', 'Kristiana', 'Kristián', 'Kristina', 'Kristýna', 'Krorona', 'Krystýna', 'Kryštof', 'Křesomysl', 'Květa', 'Květoslav', 'Květoslava', 'Kvido', 'Lada', 'Ladislav', 'Ladislava', 'Laris', 'Larisa', 'Laura', 'Lea', 'Lenka', 'Leo', 'Leon', 'Leona', 'Leonard', 'Leontina', 'Leopold', 'Leoš', 'Lešek', 'Lia', 'Liběna', 'Libor', 'Libuše', 'Lili', 'Liliana', 'Linda', 'Lipan', 'Lisa', 'Livie', 'Ljuba', 'Lorna', 'Lubomír', 'Lubor', 'Luboš', 'Lucian', 'Lucie', 'Luděk', 'Ludmila', 'Ludvík', 'Lumír', 'Lukáš', 'Lýdie', 'Magdaléna', 'Mahulena', 'Maja', 'Mája', 'Malia', 'Málie', 'Malika', 'Malvína', 'Marcel', 'Marcela', 'Marek', 'Marián', 'Mariana', 'Marie', 'Marika', 'Marin', 'Marina', 'Marisa', 'Marius', 'Markéta', 'Marlen', 'Marshall', 'Maroš', 'Marta', 'Martin', 'Martina', 'Matěj', 'Matouš', 'Matyáš', 'Matylda', 'Maxim', 'Maxmilián', 'Meda', 'Medard', 'Metoděj', 'Michael', 'Michaela', 'Michal', 'Mikeš', 'Mikuláš', 'Milada', 'Milan', 'Milena', 'Miloslav', 'Miloslava', 'Miloš', 'Miluše', 'Mircea', 'Miriam', 'Miron', 'Miroslav', 'Miroslava', 'Mlada', 'Mlhoš', 'Mnata', 'Mohamed', 'Mojmír', 'Monika', 'Muriel', 'Myra', 'Naďa', 'Naděžda', 'Napoleon', 'Narcis', 'Narcisa', 'Nastasja', 'Nastěnka', 'Natálie', 'Nataniel', 'Nataša', 'Nazarius', 'Nepomucena', 'Nepomuk', 'Neklan', 'Nela', 'Nelly', 'Nezamysl', 'Nicola', 'Nicoleta', 'Nicu', 'Niels', 'Nika', 'Nikanor', 'Nikasius', 'Nikefor', 'Nikeforos', 'Nikita', 'Nikodém', 'Nikol, Nikola', 'Nikolas (popř. Nicolas či Nicholas)', 'Nikolaus', 'Nikoleta', 'Nikolita', 'Nina', 'Ninoslav', 'Nivard', 'Noemi', 'Nonius', 'Nonna', 'Nonnosus', 'Nora', 'Norbert', 'Norman', 'Nymfa', 'Octavian', 'Odeta', 'Odin', 'Oldřich', 'Oldřiška', 'Oleg', 'Olga', 'Olimpiada', 'Olin', 'Oliver', 'Olivie', 'Ondra', 'Ondřej', 'Ondřejka', 'Orlando', 'Orlík', 'Oskar', 'Otakar', 'Otmar', 'Oto', 'Otýlie', 'Pankrác', 'Patricie', 'Patrik', 'Pavel', 'Pavla', 'Pavlín', 'Pavlína', 'Penelope', 'Peregrin', 'Petr', 'Petra', 'Petromila', 'Pia', 'Pipin', 'Pius', 'Pnina', 'Pravoslav', 'Pribin', 'Prokop', 'Prokopa', 'Přemysl', 'Quido', 'Radan', 'Radana', 'Radek', 'Radim', 'Radka', 'Radmil', 'Radmila', 'Radomil', 'Radomír', 'Radoslav', 'Radovan', 'Radu', 'Rafael', 'Raven', 'Reggie', 'Regína', 'Renáta', 'René', 'Restituta', 'Richard', 'Rita', 'Robert', 'Roberta', 'Robin', 'Rodan', 'Roderik', 'Roland', 'Roman', 'Romana', 'Ronald', 'Rosalinda', 'Rostislav', 'Rozálie', 'Rudolf', 'Rút', 'Růžena', 'Roxana', 'Řehoř', 'Řeřich', 'Saaba (Sába)', 'Sabina', 'Salome', 'Sally', 'Samir', 'Samuel', 'Sandra', 'Sante', 'Sára', 'Saskie', 'Sáva', 'Sebastian', 'Sergei', 'Servác', 'Seth', 'Silvestr', 'Silva', 'Silvia', 'Silvie', 'Simon', 'Simona', 'Slavěna', 'Slavomír', 'Soběslav', 'Soběslava', 'Sofie', 'Soňa', 'Sorin', 'Spytihněv', 'Stanislav', 'Stanislava', 'Stela', 'Stelian', 'Strachota', 'Svatava', 'Svatopluk', 'Svatoslav', 'Světlana', 'Sven', 'Sylva', 'Sylvie', 'Sanem', 'Šárka', 'Šarlota', 'Šimon', 'Šiva', 'Štefan', 'Šťáhlav', 'Štěpán', 'Štěpánka', 'Šimona', 'Tadeáš', 'Talip', 'Tamara', 'Tara', 'Tarsicius', 'Taťána', 'Tea', 'Teodor', 'Tereza', 'Terezie', 'Tibor', 'Tobiáš', 'Tomáš', 'Tomáška', 'Toni', 'Trina', 'Tristan', 'Udo', 'Ulrika', 'Ulrich', 'Uma', 'Urban', 'Uršula', 'Uvo', 'Václav', 'Václava', 'Vadim', 'Valdemar', 'Valentýn', 'Valentýna', 'Valerie', 'Valérie', 'Vanda', 'Vanesa', 'Vavřinec', 'Věnceslav', 'Vendelín', 'Vendula', 'Věra', 'Veronika', 'Věroslav', 'Viktor', 'Viktorie', 'Vili', 'Vilém', 'Vilma', 'Vilemína', 'Vincenc', 'Viola', 'Violka', 'Vít', 'Vítězslav', 'Vlad', 'Vladan', 'Vladěna', 'Vladim', 'Vladimír', 'Vladimíra', 'Vladislav', 'Vladivoj', 'Vlasta', 'Vlastimil', 'Vlastislav', 'Vnislav', 'Vojen', 'Vojtěch', 'Voršila', 'Vratislav', 'Vsevolod', 'Waldemar', 'Walter', 'Werner', 'William', 'Willow', 'Wolfgang', 'Wolfram', 'Xaver', 'Xaverie', 'Xaverius', 'Xena', 'Xenie', 'Yancy', 'Yva', 'Yvan', 'Yvana', 'Yveta', 'Záboj', 'Zachar', 'Zachariáš', 'Záviš', 'Zbislav', 'Zbyhněv', 'Zbyhněva', 'Zbyněk', 'Zbyňka', 'Zbyslav', 'Zbyslava', 'Zbyšek', 'Zbyška', 'Zdena', 'Zdeněk', 'Zdenka', 'Zdeňka', 'Zderad', 'Zdeslav', 'Zdeslava', 'Zdík', 'Zdirad', 'Zdislav', 'Zdislava', 'Zeno', 'Zenobie', 'Zenon', 'Zikmund', 'Zina', 'Zinaida', 'Zita', 'Zlata', 'Zlatan', 'Zlatko', 'Zlatomír', 'Zlatomíra', 'Zlatuše', 'Zoana', 'Zoe', 'Zoja', 'Zoltán', 'Zora', 'Zoran', 'Zoroslav', 'Zoroslava', 'Zosim', 'Zuzana', 'Zvonimír', 'Zvonimíra', 'Žakelina', 'Žakelína', 'Žaneta', 'Žarko', 'Ždan', 'Ždana', 'Želibor', 'Želimír', 'Želimíra', 'Želislav', 'Želislava', 'Želmír', 'Želmíra', 'Žibřid', 'Žitomír', 'Žitomíra', 'Žitoslav', 'Žitoslava', 'Živa', 'Živan', 'Živana', 'Žofie']
  ;
  

var validWords3 = [
  'Abertamy',
  'Adamov',
  'Andělská Hora',
  'Aš',
  'Bakov nad Jizerou',
  'Bavorov',
  'Bečov nad Teplou',
  'Bechyně',
  'Bělá nad Radbuzou',
  'Bělá pod Bezdězem',
  'Bělčice',
  'Benátky nad Jizerou',
  'Benešov',
  'Benešov nad Ploučnicí',
  'Beroun',
  'Bezdružice',
  'Bílina',
  'Bílovec',
  'Blansko',
  'Blatná',
  'Blovice',
  'Blšany',
  'Bohumín',
  'Bohušovice nad Ohří',
  'Bochov',
  'Bojkovice',
  'Bor',
  'Borohrádek',
  'Borovany',
  'Boskovice',
  'Boží Dar',
  'Brandýs nad Labem-Stará Boleslav',
  'Brandýs nad Orlicí',
  'Brno',
  'Broumov',
  'Brtnice',
  'Brumov-Bylnice',
  'Bruntál',
  'Brušperk',
  'Břeclav',
  'Březnice',
  'Březová',
  'Březová nad Svitavou',
  'Břidličná',
  'Bučovice',
  'Budišov nad Budišovkou',
  'Budyně nad Ohří',
  'Buštěhrad',
  'Bystré',
  'Bystřice',
  'Bystřice nad Pernštejnem',
  'Bystřice pod Hostýnem',
  'Bzenec',
  'Cvikov',
  'Čáslav',
  'Čelákovice',
  'Černošice',
  'Černošín',
  'Černovice',
  'Červená Řečice',
  'Červený Kostelec',
  'Česká Kamenice',
  'Česká Lípa',
  'Česká Skalice',
  'Česká Třebová',
  'České Budějovice',
  'České Velenice',
  'Český Brod',
  'Český Dub',
  'Český Krumlov',
  'Český Těšín',
  'Dačice',
  'Dašice',
  'Děčín',
  'Desná',
  'Deštná',
  'Dobrovice',
  'Dobruška',
  'Dobřany',
  'Dobřichovice',
  'Dobříš',
  'Doksy',
  'Dolní Benešov',
  'Dolní Bousov',
  'Dolní Kounice',
  'Dolní Poustevna',
  'Domažlice',
  'Dubá',
  'Dubí',
  'Dubňany',
  'Duchcov',
  'Dvůr Králové nad Labem',
  'Františkovy Lázně',
  'Frenštát pod Radhoštěm',
  'Frýdek-Místek',
  'Frýdlant',
  'Frýdlant nad Ostravicí',
  'Fryšták',
  'Fulnek',
  'Golčův Jeníkov',
  'Habartov',
  'Habry',
  'Hanušovice',
  'Harrachov',
  'Hartmanice',
  'Havířov',
  'Havlíčkův Brod',
  'Hejnice',
  'Heřmanův Městec',
  'Hlinsko',
  'Hluboká nad Vltavou',
  'Hlučín',
  'Hluk',
  'Hodkovice nad Mohelkou',
  'Hodonín',
  'Holešov',
  'Holice',
  'Holýšov',
  'Hora Svaté Kateřiny',
  'Horažďovice',
  'Horní Benešov',
  'Horní Blatná',
  'Horní Bříza',
  'Horní Cerekev',
  'Horní Jelení',
  'Horní Jiřetín',
  'Horní Planá',
  'Horní Slavkov',
  'Horšovský Týn',
  'Hořice',
  'Hořovice',
  'Hostinné',
  'Hostivice',
  'Hostomice',
  'Hostouň',
  'Hoštka',
  'Hradec Králové',
  'Hradec nad Moravicí',
  'Hrádek',
  'Hrádek nad Nisou',
  'Hranice (okres Cheb)',
  'Hranice (okres Přerov)',
  'Hrob',
  'Hrochův Týnec',
  'Hronov',
  'Hrotovice',
  'Hroznětín',
  'Hrušovany nad Jevišovkou',
  'Hulín',
  'Humpolec',
  'Husinec',
  'Hustopeče',
  'Chabařovice',
  'Cheb',
  'Chlumec',
  'Chlumec nad Cidlinou',
  'Choceň',
  'Chodov',
  'Chomutov',
  'Chotěboř',
  'Chrast',
  'Chrastava',
  'Chropyně',
  'Chrudim',
  'Chřibská',
  'Chvaletice',
  'Chýně',
  'Chýnov',
  'Chyše',
  'Ivančice',
  'Ivanovice na Hané',
  'Jablonec nad Jizerou',
  'Jablonec nad Nisou',
  'Jablonné nad Orlicí',
  'Jablonné v Podještědí',
  'Jablunkov',
  'Jáchymov',
  'Janov',
  'Janovice nad Úhlavou',
  'Janské Lázně',
  'Jaroměř',
  'Jaroměřice nad Rokytnou',
  'Javorník',
  'Jemnice',
  'Jesenice (okres Rakovník)',
  'Jesenice (okres Praha-západ)',
  'Jeseník',
  'Jevíčko',
  'Jevišovice',
  'Jičín',
  'Jihlava',
  'Jilemnice',
  'Jílové',
  'Jílové u Prahy',
  'Jindřichův Hradec',
  'Jirkov',
  'Jiříkov',
  'Jistebnice',
  'Kadaň',
  'Kamenice nad Lipou',
  'Kamenický Šenov',
  'Kaplice',
  'Kardašova Řečice',
  'Karlovy Vary',
  'Karolinka',
  'Karviná',
  'Kasejovice',
  'Kašperské Hory',
  'Kaznějov',
  'Kdyně',
  'Kelč',
  'Kladno',
  'Kladruby',
  'Klášterec nad Ohří',
  'Klatovy',
  'Klecany',
  'Klimkovice',
  'Klobouky u Brna',
  'Kojetín',
  'Kolín',
  'Konice',
  'Kopidlno',
  'Kopřivnice',
  'Koryčany',
  'Kosmonosy',
  'Kostelec na Hané',
  'Kostelec nad Černými lesy',
  'Kostelec nad Labem',
  'Kostelec nad Orlicí',
  'Košťany',
  'Kouřim',
  'Kožlany',
  'Králíky',
  'Kralovice',
  'Kralupy nad Vltavou',
  'Králův Dvůr',
  'Kraslice',
  'Krásná Hora nad Vltavou',
  'Krásná Lípa',
  'Krásné Údolí',
  'Krásno',
  'Kravaře',
  'Krnov',
  'Kroměříž',
  'Krupka',
  'Kryry',
  'Kunovice',
  'Kunštát',
  'Kuřim',
  'Kutná Hora',
  'Kyjov',
  'Kynšperk nad Ohří',
  'Lanškroun',
  'Lanžhot',
  'Lázně Bělohrad',
  'Lázně Bohdaneč',
  'Lázně Kynžvart',
  'Ledeč nad Sázavou',
  'Ledvice',
  'Letohrad',
  'Letovice',
  'Libáň',
  'Libčice nad Vltavou',
  'Liběchov',
  'Liberec',
  'Libochovice',
  'Libušín',
  'Lipnice nad Sázavou',
  'Lipník nad Bečvou',
  'Lišov',
  'Litoměřice',
  'Litomyšl',
  'Litovel',
  'Litvínov',
  'Loket',
  'Lom',
  'Lomnice nad Lužnicí',
  'Lomnice nad Popelkou',
  'Loštice',
  'Loučná pod Klínovcem',
  'Louny',
  'Lovosice',
  'Luby',
  'Lučany nad Nisou',
  'Luhačovice',
  'Luže',
  'Lysá nad Labem',
  'Manětín',
  'Mariánské Lázně',
  'Mašťov',
  'Měčín',
  'Mělník',
  'Městec Králové',
  'Město Albrechtice',
  'Město Touškov',
  'Meziboří',
  'Meziměstí',
  'Mikulášovice',
  'Mikulov',
  'Miletín',
  'Milevsko',
  'Miličín',
  'Milovice',
  'Mimoň',
  'Miroslav',
  'Mirošov',
  'Mirotice',
  'Mirovice',
  'Mladá Boleslav',
  'Mladá Vožice',
  'Mnichovice',
  'Mnichovo Hradiště',
  'Mníšek pod Brdy',
  'Modřice',
  'Mohelnice',
  'Moravská Třebová',
  'Moravské Budějovice',
  'Moravský Beroun',
  'Moravský Krumlov',
  'Morkovice-Slížany',
  'Most',
  'Mšeno',
  'Mýto',
  'Náchod',
  'Nalžovské Hory',
  'Náměšť nad Oslavou',
  'Napajedla',
  'Nasavrky',
  'Nechanice',
  'Nejdek',
  'Němčice nad Hanou',
  'Nepomuk',
  'Neratovice',
  'Netolice',
  'Neveklov',
  'Nová Bystřice',
  'Nová Paka',
  'Nová Role',
  'Nová Včelnice',
  'Nové Hrady',
  'Nové Město na Moravě',
  'Nové Město nad Metují',
  'Nové Město pod Smrkem',
  'Nové Sedlo',
  'Nové Strašecí',
  'Nový Bor',
  'Nový Bydžov',
  'Nový Jičín',
  'Nový Knín',
  'Nymburk',
  'Nýrsko',
  'Nýřany',
  'Odolena Voda',
  'Odry',
  'Olešnice',
  'Olomouc',
  'Oloví',
  'Opava',
  'Opočno',
  'Orlová',
  'Osečná',
  'Osek',
  'Oslavany',
  'Ostrava',
  'Ostrov',
  'Otrokovice',
  'Pacov',
  'Pardubice',
  'Paskov',
  'Pec pod Sněžkou',
  'Pečky',
  'Pelhřimov',
  'Petřvald',
  'Pilníkov',
  'Písek',
  'Planá',
  'Planá nad Lužnicí',
  'Plánice',
  'Plasy',
  'Plesná',
  'Plumlov',
  'Plzeň',
  'Poběžovice',
  'Počátky',
  'Podbořany',
  'Poděbrady',
  'Podivín',
  'Pohořelice',
  'Police nad Metují',
  'Polička',
  'Polná',
  'Postoloprty',
  'Potštát',
  'Praha',
  'Prachatice',
  'Proseč',
  'Prostějov',
  'Protivín',
  'Přebuz',
  'Přelouč',
  'Přerov',
  'Přeštice',
  'Příbor',
  'Příbram',
  'Přibyslav',
  'Přimda',
  'Pyšely',
  'Rabí',
  'Radnice',
  'Rájec-Jestřebí',
  'Rajhrad',
  'Rakovník',
  'Ralsko',
  'Raspenava',
  'Rejštejn',
  'Rokycany',
  'Rokytnice nad Jizerou',
  'Rokytnice v Orlických horách',
  'Ronov nad Doubravou',
  'Rosice',
  'Rotava',
  'Roudnice nad Labem',
  'Rousínov',
  'Rovensko pod Troskami',
  'Roztoky',
  'Rožmberk nad Vltavou',
  'Rožďalovice',
  'Rožmitál pod Třemšínem',
  'Rožnov pod Radhoštěm',
  'Rtyně v Podkrkonoší',
  'Rudná',
  'Rudolfov',
  'Rumburk',
  'Rychnov nad Kněžnou',
  'Rychnov u Jablonce nad Nisou',
  'Rychvald',
  'Rýmařov',
  'Řevnice',
  'Říčany',
  'Sadská',
  'Sázava',
  'Seč',
  'Sedlčany',
  'Sedlec-Prčice',
  'Sedlice',
  'Semily',
  'Sezemice',
  'Sezimovo Ústí',
  'Skalná',
  'Skuteč',
  'Slaný',
  'Slatiňany',
  'Slavičín',
  'Slavkov u Brna',
  'Slavonice',
  'Slušovice',
  'Smečno',
  'Smiřice',
  'Smržovka',
  'Soběslav',
  'Sobotka',
  'Sokolov',
  'Solnice',
  'Spálené Poříčí',
  'Staňkov',
  'Staré Město (okres Šumperk)',
  'Staré Město (okres Uherské Hradiště)',
  'Stárkov',
  'Starý Plzenec',
  'Stod',
  'Stochov',
  'Strakonice',
  'Stráž nad Nežárkou',
  'Stráž pod Ralskem',
  'Strážnice',
  'Strážov',
  'Strmilov',
  'Stříbro',
  'Studénka',
  'Suchdol nad Lužnicí',
  'Sušice',
  'Světlá nad Sázavou',
  'Svitavy',
  'Svoboda nad Úpou',
  'Svratka',
  'Šenov',
  'Šlapanice',
  'Šluknov',
  'Špindlerův Mlýn',
  'Štěpánov',
  'Šternberk',
  'Štětí',
  'Štíty',
  'Štramberk',
  'Šumperk',
  'Švihov',
  'Tábor',
  'Tachov',
  'Tanvald',
  'Telč',
  'Teplá',
  'Teplice',
  'Teplice nad Metují',
  'Terezín',
  'Tišnov',
  'Toužim',
  'Tovačov',
  'Trhové Sviny',
  'Trhový Štěpánov',
  'Trmice',
  'Trutnov',
  'Třebechovice pod Orebem',
  'Třebenice',
  'Třebíč',
  'Třeboň',
  'Třemošná',
  'Třemošnice',
  'Třešť',
  'Třinec',
  'Turnov',
  'Týn nad Vltavou',
  'Týnec nad Labem',
  'Týnec nad Sázavou',
  'Týniště nad Orlicí',
  'Uherské Hradiště',
  'Uherský Brod',
  'Uherský Ostroh',
  'Uhlířské Janovice',
  'Unhošť',
  'Uničov',
  'Újezd u Brna',
  'Úpice',
  'Úsov',
  'Ústí nad Labem',
  'Ústí nad Orlicí',
  'Úštěk',
  'Úterý',
  'Úvaly',
  'Valašské Klobouky',
  'Valašské Meziříčí',
  'Valtice',
  'Vamberk',
  'Varnsdorf',
  'Vejprty',
  'Velešín',
  'Velká Bíteš',
  'Velká Bystřice',
  'Velké Bílovice',
  'Velké Hamry',
  'Velké Meziříčí',
  'Velké Opatovice',
  'Velké Pavlovice',
  'Velký Šenov',
  'Veltrusy',
  'Velvary',
  'Verneřice',
  'Veselí nad Lužnicí',
  'Veselí nad Moravou',
  'Veverská Bítýška',
  'Větřní',
  'Vidnava',
  'Vimperk',
  'Vítkov',
  'Vizovice',
  'Vlachovo Březí',
  'Vlašim',
  'Vodňany',
  'Volary',
  'Volyně',
  'Votice',
  'Vracov',
  'Vratimov',
  'Vrbno pod Pradědem',
  'Vrchlabí',
  'Vroutek',
  'Vsetín',
  'Všeruby',
  'Výsluní',
  'Vysoké Mýto',
  'Vysoké nad Jizerou',
  'Vysoké Veselí',
  'Vyškov',
  'Vyšší Brod',
  'Zábřeh',
  'Zákupy',
  'Zásmuky',
  'Zbiroh',
  'Zbýšov',
  'Zdice',
  'Zlaté Hory',
  'Zlín',
  'Zliv',
  'Znojmo',
  'Zruč nad Sázavou',
  'Zubří',
  'Žacléř',
  'Žamberk',
  'Žandov',
  'Žatec',
  'Ždánice',
  'Žďár nad Sázavou',
  'Ždírec nad Doubravou',
  'Žebrák',
  'Železná Ruda',
  'Železnice',
  'Železný Brod',
  'Židlochovice',
  'Žirovnice',
  'Žlutice',
  'Žulová'
];
var score = 0; // Initialize score
var generatedLetter = ''; // Variable to store the randomly generated letter

function checkWord() {
  const countryInput = document.getElementById("userInput").value;
  const animalInput = document.getElementById("userInput2").value;
  const cityInput = document.getElementById("userInput3").value;
  const resultDiv = document.getElementById("result"); // Get result div

  // Check for country input
  if (validWords.includes(countryInput) && countryInput.startsWith(generatedLetter)) {
      score += 10; // Add 10 points if the country is valid and starts with the generated letter
      resultDiv.textContent = "The country name is valid and starts with the correct letter!";
  } else if (validWords.includes(countryInput)) {
      resultDiv.textContent = "The country name is valid!";
  }

  // Check for animal input
  if (validWords2.includes(animalInput) && animalInput.startsWith(generatedLetter)) {
      score += 10; // Add 10 points if the animal is valid and starts with the generated letter
      resultDiv.textContent = "The animal name is valid and starts with the correct letter!";
  } else if (validWords2.includes(animalInput)) {
      resultDiv.textContent = "The animal name is valid!";
  }

  // Check for city input
  if (validWords3.includes(cityInput) && cityInput.startsWith(generatedLetter)) {
      score += 10; // Add 10 points if the city is valid and starts with the generated letter
      resultDiv.textContent = "The city name is valid and starts with the correct letter!";
  } else if (validWords3.includes(cityInput)) {
      resultDiv.textContent = "The city name is valid!";
  }

  // Update score display
  document.getElementById("score").textContent = score; 
  // Clear input fields
  document.getElementById("userInput").value = ''; 
  document.getElementById("userInput2").value = ''; 
  document.getElementById("userInput3").value = ''; 
}

var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
var i = 0;
var intervalID;
var usedLetters = new Set(); // Set to track used letters

function startGenerating() {
  clearInterval(intervalID);
  usedLetters.clear(); // Clear the set for new session

  intervalID = setInterval(function() {
      document.getElementById("alpha").innerHTML = alphabet[i];
      i++;
      if (i === alphabet.length) {
          i = 0; // Reset to start of the alphabet
      }
  }, 100); // Change letter every 100 ms

  setTimeout(stopGenerating, 1000); // Adjust how long it loops
}

function stopGenerating() {
  clearInterval(intervalID);
  
  let randomIndex = Math.floor(Math.random() * alphabet.length);
  generatedLetter = alphabet[randomIndex]; // Store the randomly generated letter
  document.getElementById("alpha").innerHTML = generatedLetter; // Display the letter
}

// Timer setup
const mindiv = document.querySelector(".mins");
const secdiv = document.querySelector(".secs");
const bell = document.querySelector("audio");
const startBtn = document.querySelector(".start");
let initial, mins, seconds;

startBtn.addEventListener("click", () => {
  mins = +document.getElementById("focusTime").value || 1;
  seconds = mins * 60;
  startGenerating(); // Start generating letters
  decremenT(); // Start the timer
  startBtn.style.transform = "scale(0)"; // Hide the start button
});

function decremenT() {
  mindiv.textContent = Math.floor(seconds / 60);
  secdiv.textContent = seconds % 60 > 9 ? seconds % 60 : `0${seconds % 60}`;

  if (seconds > 0) {
      seconds--;
      setTimeout(decremenT, 1000);
  } else {
      bell.play();
      checkWord(); // Call checkWord function when timer runs out
      startBtn.style.transform = "scale(1)"; // Show the start button again
  }
}

document.querySelector("form").addEventListener("submit", (e) => {
  e.preventDefault();
  localStorage.setItem("focusTime", document.getElementById("focusTime").value);
});